trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-durable-function-trace - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Rutz Internal Demo Account (164a84cf-b099-4567-a527-c2a8143a32c7)'

stages:
 - stage: CI
   displayName: CI stage 
   variables:
     app-name: 'demo-az-durable-function-trace'
     storageAccountName: 'azfuncddftci'
     region: 'Central US'
     resourceGroupName: 'demo-az-durable-function-trace'  
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
           
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create Function Infrastructure'
              inputs:
                azureSubscription: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-appName $(app-name) -storageAccountName $(storageAccountName)'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - task: AzureFunctionApp@1
              displayName: '5. Azure functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionApp
                appName: $(app-name)
                package: '$(Pipeline.Workspace)/build/App/demo-az-durable-functions.zip'